name: Live
on:
  workflow_dispatch:
    inputs:
      repo:
        description: "repo"
        default: "raiblocksone/raiblocksone-node"
        required: true
      ref:
        description: "tag to build"
        default: "develop"
        required: true
env:
  artifact: 1

jobs:

  linux_docker_job:
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    steps:
      - name: tag
        run: |
          echo "TAG=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.1.0
        with:
          submodules: "recursive"
          ref: ${{ github.event.inputs.ref }}
          repository: ${{ github.event.inputs.repo }}
      - name: Fetch Deps
        env:
          COMPILER: gcc
        run: ci/actions/linux/install_deps.sh
      - name: Build Docker (raiblocksone/raiblocksone)
        run: CI_TAG=${TAG} ci/actions/linux/docker-build.sh
      - name: Deploy Docker Hub (raiblocksone/raiblocksone)
        if: ${{ github.repository == 'raiblocksone/raiblocksone-node' }}
        run: CI_TAG=${TAG} ci/actions/linux/docker-deploy.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to ghcr.io
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a #v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Docker (ghcr.io)
        run: ci/actions/linux/ghcr_push.sh
